# -*- coding: utf-8 -*-
"""SEM_WHEEL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZBC6X6ZGP6d8OtsMt3re1Ti6OurtI40m
"""

!pip install opencv-python-headless scikit-image matplotlib

!pip install scikit-learn

import cv2
import numpy as np
import matplotlib.pyplot as plt

from skimage.measure import regionprops

from google.colab import files
uploaded = files.upload()

original_image = cv2.imread(list(uploaded.keys())[0])
original_image = cv2.cvtColor(original_image, cv2.COLOR_BGR2RGB)

plt.figure(figsize=(6,6))
plt.imshow(original_image)
plt.title("Original SEM Image")
plt.axis("off")

gray = cv2.cvtColor(original_image, cv2.COLOR_RGB2GRAY)

edges = cv2.Canny(gray,50,150)

h,w = edges.shape

row_strength = np.sum(edges,axis=1)

row_strength = cv2.GaussianBlur(
    row_strength.reshape(-1,1),
    (51,1),
    0
).flatten()

row_strength = row_strength / np.max(row_strength)

candidate_rows = np.where(row_strength > 0.25)[0]
candidate_rows = candidate_rows[candidate_rows > int(0.6*h)]

metadata_top = np.min(candidate_rows)

print("Metadata starts at row:", metadata_top)

cropped = original_image[:metadata_top,:]

plt.figure(figsize=(6,6))
plt.imshow(cropped)
plt.title("Metadata Removed")
plt.axis("off")

clean_image = cropped.copy()

h_img,w_img,_ = clean_image.shape

clean_image[int(0.85*h_img):h_img,0:int(0.25*w_img)] = 0

# -------- Detect scale bar length automatically --------
gray_scale = cv2.cvtColor(original_image, cv2.COLOR_RGB2GRAY)

# detect bright objects (scale bar)
_, thresh = cv2.threshold(gray_scale, 200, 255, cv2.THRESH_BINARY)

# morphological operation to keep horizontal bars
kernel = cv2.getStructuringElement(cv2.MORPH_RECT,(40,3))
horizontal = cv2.morphologyEx(thresh, cv2.MORPH_OPEN, kernel)

contours,_ = cv2.findContours(horizontal, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

scale_length_pixels = None

h_img = original_image.shape[0]

for c in contours:
    x,y,w,h = cv2.boundingRect(c)

    aspect_ratio = w / max(h,1)

    # scale bars are long horizontal rectangles near bottom
    if aspect_ratio > 5 and w > 50 and y > 0.7*h_img:
        scale_length_pixels = w
        break

print("Scale bar length (pixels):", scale_length_pixels)

if scale_length_pixels is None:
    raise ValueError("Scale bar not detected")









gray_clean = cv2.cvtColor(clean_image,cv2.COLOR_RGB2GRAY)

plt.imshow(gray_clean,cmap="gray")
plt.title("Grayscale SEM")
plt.axis("off")

gray_clean = cv2.equalizeHist(gray_clean)

plt.figure(figsize=(6,6))
plt.imshow(gray_clean,cmap="gray")
plt.title("Normalized SEM")
plt.axis("off")

blur = cv2.GaussianBlur(gray_clean,(7,7),0)

plt.imshow(blur,cmap="gray")
plt.title("Blurred SEM")
plt.axis("off")

binary = cv2.adaptiveThreshold(
    blur,
    255,
    cv2.ADAPTIVE_THRESH_GAUSSIAN_C,
    cv2.THRESH_BINARY,
    51,
    -5
)

plt.imshow(binary,cmap="gray")
plt.title("Binary Segmentation")
plt.axis("off")

kernel = cv2.getStructuringElement(cv2.MORPH_ELLIPSE,(7,7))

binary = cv2.morphologyEx(binary,cv2.MORPH_OPEN,kernel,iterations=2)
binary = cv2.morphologyEx(binary,cv2.MORPH_CLOSE,kernel,iterations=2)

plt.imshow(binary,cmap="gray")
plt.title("Clean Binary Mask")
plt.axis("off")

dist = cv2.distanceTransform(binary,cv2.DIST_L2,5)

plt.imshow(dist,cmap="jet")
plt.title("Distance Transform")
plt.axis("off")

from skimage.feature import peak_local_max

coords = peak_local_max(
    dist,
    min_distance=25,
    threshold_rel=0.2
)

plt.imshow(clean_image)

ys, xs = coords[:,0], coords[:,1]

plt.scatter(xs,ys,c="red",s=10)

plt.title("Detected Grit Centers")
plt.axis("off")

from scipy import ndimage

markers = np.zeros(dist.shape,dtype=int)

for i,(y,x) in enumerate(coords):
    markers[y,x] = i+1

markers = ndimage.label(markers)[0]

print("Detected centers:",markers.max())

from scipy import ndimage
from skimage.feature import peak_local_max
from skimage.segmentation import watershed

# compute gradient image
gradient = cv2.morphologyEx(
    gray_clean,
    cv2.MORPH_GRADIENT,
    np.ones((3,3),np.uint8)
)

plt.imshow(gradient,cmap='gray')
plt.title("Gradient Image")
plt.axis("off")

_, binary = cv2.threshold(
    gray_clean,
    0,
    255,
    cv2.THRESH_BINARY + cv2.THRESH_OTSU
)

binary = cv2.morphologyEx(
    binary,
    cv2.MORPH_OPEN,
    np.ones((5,5),np.uint8),
    iterations=2
)

plt.imshow(binary,cmap='gray')
plt.title("Binary Mask")
plt.axis("off")

from scipy import ndimage

# fill holes inside grains
binary = ndimage.binary_fill_holes(binary).astype(np.uint8)*255

# remove small internal regions
kernel = np.ones((7,7),np.uint8)

binary = cv2.morphologyEx(
    binary,
    cv2.MORPH_CLOSE,
    kernel,
    iterations=2
)

# smooth edges
binary = cv2.morphologyEx(
    binary,
    cv2.MORPH_OPEN,
    kernel,
    iterations=1
)

plt.figure(figsize=(6,6))
plt.imshow(binary,cmap="gray")
plt.title("Cleaned Grain Mask")
plt.axis("off")

from scipy import ndimage
from skimage.feature import peak_local_max
from skimage.segmentation import watershed

# ---------- STEP 1: edge detection ----------
edges = cv2.Canny(gray_clean, 40, 160)

plt.figure(figsize=(6,6))
plt.imshow(edges, cmap='gray')
plt.title("Detected Edges")
plt.axis("off")


# ---------- STEP 2: create grain mask ----------
_, binary = cv2.threshold(
    gray_clean,
    0,
    255,
    cv2.THRESH_BINARY + cv2.THRESH_OTSU
)

# remove small noise
kernel = np.ones((5,5),np.uint8)
binary = cv2.morphologyEx(binary, cv2.MORPH_CLOSE, kernel, iterations=2)

# fill holes inside grains
binary = ndimage.binary_fill_holes(binary).astype(np.uint8)

plt.figure(figsize=(6,6))
plt.imshow(binary,cmap='gray')
plt.title("Clean Grain Mask")
plt.axis("off")


# ---------- STEP 3: distance transform ----------
dist = cv2.distanceTransform(binary, cv2.DIST_L2,5)

plt.figure(figsize=(6,6))
plt.imshow(dist,cmap='jet')
plt.title("Distance Transform")
plt.axis("off")


# ---------- STEP 4: detect grain centers ----------
coords = peak_local_max(
    dist,
    min_distance=30,
    labels=binary
)

mask = np.zeros(dist.shape,dtype=bool)
mask[tuple(coords.T)] = True

markers,_ = ndimage.label(mask)


# ---------- STEP 5: watershed using edges ----------
labels = watershed(
    edges,
    markers,
    mask=binary
)

regions = regionprops(labels)

from skimage.measure import regionprops

regions = regionprops(labels)

grit_masks = []

for r in regions:

    if r.area < 800:
        continue

    mask = (labels == r.label)

    grit_masks.append(mask)

print("Detected grits:", len(grit_masks))

detected_image = clean_image.copy()

for mask in grit_masks:

    mask_uint8 = (mask.astype(np.uint8) * 255)

    contours,_ = cv2.findContours(
        mask_uint8,
        cv2.RETR_EXTERNAL,
        cv2.CHAIN_APPROX_SIMPLE
    )

    if len(contours) == 0:
        continue

    cnt = max(contours, key=cv2.contourArea)

    cv2.drawContours(
        detected_image,
        [cnt],
        -1,
        (0,255,0),
        2
    )

plt.figure(figsize=(8,8))
plt.imshow(detected_image)
plt.title("Detected Grits")
plt.axis("off")

# -------- Convert pixels to microns --------
scale_bar_microns = 2.0  # SEM shows 2 µm scale

microns_per_pixel = scale_bar_microns / scale_length_pixels

print("Microns per pixel:", microns_per_pixel)

facet_image = clean_image.copy()

for mask in grit_masks:

    mask_uint8 = (mask.astype(np.uint8) * 255)

    contours,_ = cv2.findContours(
        mask_uint8,
        cv2.RETR_EXTERNAL,
        cv2.CHAIN_APPROX_NONE
    )

    if len(contours) == 0:
        continue

    cnt = max(contours, key=cv2.contourArea)

    hull = cv2.convexHull(cnt)

    epsilon = 0.04 * cv2.arcLength(hull, True)
    approx = cv2.approxPolyDP(hull, epsilon, True)

    cv2.drawContours(facet_image,[approx],-1,(0,255,255),2)

    for i in range(len(approx)):

        p1 = approx[i][0]
        p2 = approx[(i+1)%len(approx)][0]

        x1,y1 = p1
        x2,y2 = p2

        # length in pixels
        length_pixels = np.sqrt((x2-x1)**2 + (y2-y1)**2)

        # convert to microns
        length_um = length_pixels * microns_per_pixel

        # ignore tiny edges
        if length_um < 0.05:
            continue

        cv2.line(
            facet_image,
            (x1,y1),
            (x2,y2),
            (255,0,0),
            2
        )

        mx = int((x1+x2)/2)
        my = int((y1+y2)/2)

        label = f"{length_um:.2f} um"

        cv2.putText(
            facet_image,
            label,
            (mx,my),
            cv2.FONT_HERSHEY_SIMPLEX,
            0.4,
            (255,255,255),
            1
        )

plt.figure(figsize=(8,8))
plt.imshow(facet_image)
plt.title("Facet Edge Measurements")
plt.axis("off")

facet_image = clean_image.copy()

for mask in grit_masks:

    mask_uint8 = (mask.astype(np.uint8) * 255)

    contours,_ = cv2.findContours(
        mask_uint8,
        cv2.RETR_EXTERNAL,
        cv2.CHAIN_APPROX_NONE
    )

    if len(contours) == 0:
        continue

    cnt = max(contours, key=cv2.contourArea)

    hull = cv2.convexHull(cnt)

    epsilon = 0.04 * cv2.arcLength(hull, True)
    approx = cv2.approxPolyDP(hull, epsilon, True)

    cv2.drawContours(facet_image,[approx],-1,(0,255,255),2)

    for i in range(len(approx)):

        p1 = approx[i][0]
        p2 = approx[(i+1)%len(approx)][0]

        x1,y1 = p1
        x2,y2 = p2

        length_pixels = np.sqrt((x2-x1)**2 + (y2-y1)**2)

        length_um = length_pixels * microns_per_pixel

        if length_um < 0.05:
            continue

        cv2.line(facet_image,(x1,y1),(x2,y2),(255,0,0),2)

        mx = int((x1+x2)/2)
        my = int((y1+y2)/2)

        label = f"{length_um:.2f} um"

        cv2.putText(
            facet_image,
            label,
            (mx,my),
            cv2.FONT_HERSHEY_SIMPLEX,
            0.4,
            (255,255,255),
            1
        )

plt.figure(figsize=(8,8))
plt.imshow(facet_image)
plt.title("Facet Edge Measurements (um)")
plt.axis("off")

plt.figure(figsize=(8,8))
plt.imshow(facet_image)
plt.title("Facet Edge Measurements (um)")
plt.axis("off")

##now the construction of CAD will the there

!pip install trimesh shapely

!pip install mapbox-earcut

!pip install mapbox-earcut shapely trimesh

import trimesh
import mapbox_earcut
from shapely.geometry import Polygon

import trimesh
import numpy as np
from shapely.geometry import Polygon

solids = []

for mask in grit_masks:

    mask_uint8 = (mask.astype(np.uint8) * 255)

    contours,_ = cv2.findContours(
        mask_uint8,
        cv2.RETR_EXTERNAL,
        cv2.CHAIN_APPROX_SIMPLE
    )

    if len(contours) == 0:
        continue

    cnt = max(contours, key=cv2.contourArea)

    hull = cv2.convexHull(cnt)

    epsilon = 0.04 * cv2.arcLength(hull, True)
    approx = cv2.approxPolyDP(hull, epsilon, True)

    # -----------------------------
    # base polygon in microns
    # -----------------------------

    base_points = []

    for p in approx:
        x,y = p[0]

        base_points.append([
            x * microns_per_pixel,
            y * microns_per_pixel
        ])

    if len(base_points) < 3:
        continue

    polygon = Polygon(base_points)

    min_x, min_y, max_x, max_y = polygon.bounds

    grain_width = max(max_x-min_x, max_y-min_y)

    # realistic grain height
    height = grain_width * np.random.uniform(0.35,0.55)

    # -----------------------------
    # extrude base polygon
    # -----------------------------

    mesh = trimesh.creation.extrude_polygon(
        polygon,
        height
    )

    # -----------------------------
    # distort vertices to create facets
    # -----------------------------

    verts = mesh.vertices.copy()

    for i,v in enumerate(verts):

        # only distort upper vertices
        if v[2] > height * 0.3:

            verts[i][0] += np.random.uniform(-0.15,0.15) * grain_width
            verts[i][1] += np.random.uniform(-0.15,0.15) * grain_width
            verts[i][2] += np.random.uniform(-0.2,0.2) * height

    mesh.vertices = verts

    # -----------------------------
    # random grain orientation
    # -----------------------------

    angles = np.random.uniform(0, np.pi, 3)

    Rx = trimesh.transformations.rotation_matrix(
        angles[0],[1,0,0]
    )

    Ry = trimesh.transformations.rotation_matrix(
        angles[1],[0,1,0]
    )

    Rz = trimesh.transformations.rotation_matrix(
        angles[2],[0,0,1]
    )

    mesh.apply_transform(Rx)
    mesh.apply_transform(Ry)
    mesh.apply_transform(Rz)

    solids.append(mesh)


    plane_grains = []

spacing = 5  # microns

cols = int(np.ceil(np.sqrt(len(solids))))

row = 0
col = 0

for i, mesh in enumerate(solids):

    g = mesh.copy()

    # bring lowest point to Z = 0
    min_z = g.vertices[:,2].min()
    g.vertices[:,2] -= min_z

    # compute size
    min_x = g.vertices[:,0].min()
    max_x = g.vertices[:,0].max()

    min_y = g.vertices[:,1].min()
    max_y = g.vertices[:,1].max()

    width = max_x - min_x
    depth = max_y - min_y

    # compute grid position
    x_offset = col * (width + spacing)
    y_offset = row * (depth + spacing)

    g.vertices[:,0] += x_offset - min_x
    g.vertices[:,1] += y_offset - min_y

    plane_grains.append(g)

    col += 1

    if col >= cols:
        col = 0
        row += 1

print("Generated grains:", len(solids))

if len(solids) > 0:

    combined = trimesh.util.concatenate(solids)

    combined.export("grains.stl")

    print("Export successful")

else:
    print("No grains generated")

combined = trimesh.util.concatenate(solids)

combined.export("grit_model.stl")

plane = trimesh.util.concatenate(plane_grains)
plane.export("grains_on_plane.stl")

from google.colab import files
files.download("grit_model.stl")

from google.colab import files
files.download("grains_on_plane.stl")

print("Total grains detected:", len(solids))

for i, g in enumerate(solids[:5]):
    print("grain", i, "vertices:", len(g.vertices))

import trimesh
import numpy as np

# -----------------------------------------
# 1. Inputs (in mm)
# -----------------------------------------

wheel_diameter_mm = float(input("Enter grinding wheel diameter (mm): "))
wheel_width_mm = float(input("Enter grinding wheel width (mm): "))

# convert to microns
wheel_radius = (wheel_diameter_mm * 1000) / 2
wheel_width = wheel_width_mm * 1000

print("Wheel radius (µm):", wheel_radius)
print("Wheel width (µm):", wheel_width)

# -----------------------------------------
# 2. Create wheel body
# -----------------------------------------

wheel = trimesh.creation.cylinder(
    radius=wheel_radius,
    height=wheel_width,
    sections=128
)

# rotate wheel axis to X direction
R = trimesh.transformations.rotation_matrix(
    np.pi/2,
    [0,1,0]
)

wheel.apply_transform(R)

placed_grains = []

# -----------------------------------------
# 3. Grain density model
# -----------------------------------------

grain_density = float(input("Enter grain density (grains per mm²): "))


surface_area_mm2 = 2 * np.pi * (wheel_radius/1000) * (wheel_width/1000)

num_grains = int(surface_area_mm2 * grain_density)

print("Wheel surface area (mm²):", surface_area_mm2)
print("Total grains to generate:", num_grains)
# -----------------------------------------
# 4. Place grains
# -----------------------------------------

for i in range(num_grains):

    grain = np.random.choice(solids)
    g = grain.copy()

    # center grain
    mesh_center = g.bounds.mean(axis=0)
    g.vertices -= mesh_center

    # random orientation
    angles = np.random.uniform(0, 2*np.pi, 3)
    R = trimesh.transformations.euler_matrix(*angles)
    g.apply_transform(R)

    # grain radial size
    radial_dist = np.sqrt(g.vertices[:,1]**2 + g.vertices[:,2]**2)
    grain_radius = radial_dist.max()

    # embed grain into bond
    embed_fraction = np.random.uniform(0.3, 0.6)

    r = wheel_radius - grain_radius * embed_fraction

    # angular location
    theta = np.random.uniform(0, 2*np.pi)

    y = r * np.cos(theta)
    z = r * np.sin(theta)

    # position along wheel width
    x = np.random.uniform(-wheel_width/2, wheel_width/2)

    g.apply_translation([x,y,z])

    placed_grains.append(g)

# -----------------------------------------
# 5. Combine meshes
# -----------------------------------------

all_meshes = [wheel] + placed_grains

grinding_wheel = trimesh.util.concatenate(all_meshes)

# -----------------------------------------
# 6. Export STL
# -----------------------------------------

grinding_wheel.export("grinding_wheel_perfect.stl")

print(f"Success! {len(placed_grains)} grains placed on wheel surface.")

from google.colab import files
files.download("grinding_wheel_perfect.stl")